# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2016, 4, 10, 7, 8, 14, 931544, tzinfo=utc))),
            ],
        ),
    ]
