# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 7, 13, 6, 822730, tzinfo=utc)),
        ),
    ]
